default: true

# Disable line length checks to keep README readable in raw form
MD013: false

# Allow inline HTML fragments (common in READMEs)
MD033: false

# First line should be a top-level heading: relax for CHANGELOG, etc.
MD041: false
