version: "3.9"

services:
  urnet-client:
    # Pull a published image by default (override with URNETWORK_IMAGE env var)
    image: ${URNETWORK_IMAGE:-ghcr.io/devrandom0/urnetwork-client:latest}
    container_name: urnet-client
    environment:
      - URNETWORK_USERNAME=${URNETWORK_USERNAME:-}
      - URNETWORK_PASSWORD=${URNETWORK_PASSWORD:-}
      - URNETWORK_HOME=/data/.urnetwork
    volumes:
      - urnet-data:/data
      # Optional: persist a custom log file outside the container
      # - ./logs:/logs
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    network_mode: host
    restart: unless-stopped
    # Example: pass flags to the client
    # command: ["--help"]

    # To build locally instead of pulling, comment out the image: line above and
    # uncomment the following build context that uses the repo's Dockerfile.
    # build:
    #   context: .
    #   dockerfile: Dockerfile

volumes:
  urnet-data:
    driver: local
