services:
  urnet-client:
    network_mode: bridge
    dns:
      - 8.8.8.8
    # Docker Desktop on macOS does not support host networking; map the SOCKS port instead
    ports:
      - "1080:1080"
    # Ensure TUN setup works in the Linux VM
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    # Start VPN + SOCKS together. Provide credentials via env or pre-saved JWT in /data/.urnetwork/jwt
    command:
      - quick-connect
      - --tun=urnet0
      - --default_route
      - --exclude_route=8.8.8.8/32
      - --dns=8.8.8.8
      - --socks=0.0.0.0:1080
      - --log_level=info
