name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver version to tag (e.g., 1.2.3)'
        required: false
        type: string
      ref:
        description: 'Git ref to tag (branch name or full sha). Default: main'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  GO_VERSION: '1.24.x'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: gofmt
        run: |
          fmt_out=$(gofmt -s -l .)
          if [ -n "$fmt_out" ]; then
            echo "gofmt found issues:" && echo "$fmt_out"
            exit 1
          fi
      - name: go vet
        run: go vet ./...

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Build
        run: make build
      - name: Test
        run: make test

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request'
    env:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/urnetwork-client
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            # Add semantic version tags when pushing a tag like v1.2.3
            # Produces: 1.2.3, 1.2, 1
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
      - name: Log in to GHCR (PAT)
        if: (startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/')) && env.GHCR_TOKEN != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_TOKEN }}
      - name: Log in to GHCR (GITHUB_TOKEN)
        if: (startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/')) && env.GHCR_TOKEN == ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          cache-from: |
            type=gha
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/urnetwork-client:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/urnetwork-client:buildcache,mode=max

  publish-images-on-release:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.released == 'true'
    env:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR (PAT)
        if: env.GHCR_TOKEN != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_TOKEN }}
      - name: Log in to GHCR (GITHUB_TOKEN)
        if: env.GHCR_TOKEN == ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (release tag)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/urnetwork-client:${{ needs.release.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/urnetwork-client:${{ needs.release.outputs.tag }}
          cache-from: |
            type=gha
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/urnetwork-client:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/urnetwork-client:buildcache,mode=max

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write  # needed to create tags and releases
    outputs:
      released: ${{ steps.semrel.outputs.new_release_published }}
      version: ${{ steps.semrel.outputs.new_release_version }}
      tag: ${{ steps.semrel.outputs.new_release_git_tag }}
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Semantic Release
        id: semrel
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  force-tag-and-publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.version != ''
    permissions:
      contents: write
      packages: write
    env:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Resolve target ref
        id: ref
        run: |
          target_ref="${{ inputs.ref }}"
          if [ -z "$target_ref" ]; then target_ref="main"; fi
          git fetch origin "$target_ref" --depth=1 || true
          if git show-ref --verify --quiet "refs/heads/$target_ref"; then
            sha=$(git rev-parse "refs/remotes/origin/$target_ref")
          else
            # try resolve as sha or tag
            sha=$(git rev-parse "$target_ref^{commit}")
          fi
          echo "sha=$sha" >> $GITHUB_OUTPUT
      - name: Create git tag v${{ inputs.version }}
        uses: actions/github-script@v7
        with:
          script: |
            const version = core.getInput('version');
            const sha = core.getInput('sha');
            const tag = `v${version}`;
            try {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${tag}`,
                sha
              });
              core.notice(`Created tag ${tag} at ${sha}`);
            } catch (e) {
              if (e.status === 422) {
                core.warning(`Tag ${tag} already exists; continuing`);
              } else {
                throw e;
              }
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
        env:
          version: ${{ inputs.version }}
          sha: ${{ steps.ref.outputs.sha }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR (PAT)
        if: env.GHCR_TOKEN != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_TOKEN }}
      - name: Log in to GHCR (GITHUB_TOKEN)
        if: env.GHCR_TOKEN == ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (forced tag)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/urnetwork-client:${{ inputs.version }}
            ghcr.io/${{ github.repository_owner }}/urnetwork-client:v${{ inputs.version }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          cache-from: |
            type=gha
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/urnetwork-client:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/urnetwork-client:buildcache,mode=max
